#!/bin/bash

# I nodi avranno pid = al proprio indirizzo (nel grafo finale)
# Gli indirizzi sono nella topologia 3,2,2 cioè 0-7 al livello 0, 0-3 ai livelli 1 e 2.
# Ad esempio il pid=100 avrà indirizzo :1:0:0 e il pid=530 avrà indirizzo :5:3:0.
# (notare che il primo numero indica il livello 0 e man mano si sale)

# La topologia del g-nodo :0:0 è
#
# 6 - 7 - 1 - 5
#   \ |   |
#     2 - 3
#
# Nasce prima 1 con indirizzo :1:0:0.
# Poi entrano in sequenza come singoli nodi 3, 2, 7.
# Poi entrano contemporaneamente come singoli nodi 5, 6.

# La topologia del g-nodo :1:0 è
#
# 3 - 4 - 2
#
# Nasce prima 4 con indirizzo :4:2:2.
# Poi entrano in sequenza come singoli nodi 2, 3.
# Poi tutto il g-nodo entra nella rete finale
#  assumendo indirizzo :1:0
#  per mezzo dell'arco 700-310.

# La topologia del g-nodo :3:0 è
#
# 4 - 5 - 6 - 7
#
# Nasce prima 4 con indirizzo :4:0:0.
# Poi entrano in sequenza come singoli nodi 5, 6, 7.
# Poi tutto il g-nodo entra nella rete finale
#  assumendo indirizzo :3:0
#  per mezzo degli archi 210-430 , 500-530 e 300-730.

# In seguito si rimuove l'arco 430-530 e assistiamo
#  al rilevamento dello split del g-nodo :3:0
#  da parte dei nodi vicini 300 e 500.

# Come conseguenza diamo il comando exit_network all'isola meno anziana
#  meno anziana (cioè 530+630+730) e assistiamo
#  alla loro rimozione degli archi esterni.

radio_domain -i 100_wl0 -o 300_wl0 -o 700_wl0 -o 500_wl0 &
RADIO_100_PID=$!
radio_domain -i 300_wl0 -o 100_wl0 -o 200_wl0 -o 730_wl0 &
RADIO_300_PID=$!
radio_domain -i 200_wl0 -o 300_wl0 -o 700_wl0 -o 600_wl0 &
RADIO_200_PID=$!
radio_domain -i 700_wl0 -o 100_wl0 -o 200_wl0 -o 600_wl0 -o 310_wl0 &
RADIO_700_PID=$!
radio_domain -i 600_wl0 -o 200_wl0 -o 700_wl0 &
RADIO_600_PID=$!
radio_domain -i 500_wl0 -o 100_wl0 -o 530_wl0 &
RADIO_500_PID=$!

radio_domain -i 410_wl0 -o 210_wl0 -o 310_wl0 &
RADIO_410_PID=$!
radio_domain -i 210_wl0 -o 410_wl0 -o 430_wl0 &
RADIO_210_PID=$!
radio_domain -i 310_wl0 -o 410_wl0 -o 700_wl0 &
RADIO_310_PID=$!

radio_domain -i 430_wl0 -o 530_wl0 -o 210_wl0 &
RADIO_430_PID=$!
radio_domain -i 530_wl0 -o 430_wl0 -o 630_wl0 -o 500_wl0 &
RADIO_530_PID=$!
radio_domain -i 630_wl0 -o 530_wl0 -o 730_wl0 &
RADIO_630_PID=$!
radio_domain -i 730_wl0 -o 630_wl0 -o 300_wl0 &
RADIO_730_PID=$!


sleep 0.3

echo Starting launches at `date +%T.%N`

./system_peer --topology 3,2,2 --firstaddr 1,0,0 \
              -p 100 -i wl0 -a wl0,300,wl0,2000 -a wl0,700,wl0,2000 -a wl0,500,wl0,2000 \
              -t add_identityarc,400,0,0+1 \
              -t add_qspnarc,490,0,0+1 \
              -t add_identityarc,800,0,1+1 \
              -t add_qspnarc,890,0,1+1 \
              -t add_identityarc,1000,0,2+1 \
              -t add_qspnarc,1090,0,2+1 \
              > test_graph_pid100_out.txt 2>&1 &
PEER_100_PID=$!

./system_peer --topology 3,2,2 \
              -p 300 -i wl0 -a wl0,100,wl0,2000 -a wl0,200,wl0,2000 -a wl0,730,wl0,2000 \
              -t add_identity,400,0,1,3,0+0 \
              -t enter_net,480,0,1,0,3:0:0,1:0:0,0+0 \
              -t add_identityarc,600,1,1+1 \
              -t add_qspnarc,690,1,1+1 \
              -t add_identityarc,1400,1,2+2 \
              -t add_qspnarc,1490,1,2+2 \
              -t check_destnum,3800,1,7,300_knows_5_plus_2 \
              -t check_signal_gnode_split,3800,1,1 \
              > test_graph_pid300_out.txt 2>&1 &
PEER_300_PID=$!

./system_peer --topology 3,2,2 \
              -p 200 -i wl0 -a wl0,300,wl0,2000 -a wl0,700,wl0,2000 -a wl0,600,wl0,2000 \
              -t add_identity,600,0,1,3,0+1 \
              -t enter_net,680,0,1,0,2:0:0,2:0:0,0+1 \
              -t add_identityarc,800,1,1+1 \
              -t add_qspnarc,890,1,1+1 \
              -t add_identityarc,1000,1,2+1 \
              -t add_qspnarc,1090,1,2+1 \
              > test_graph_pid200_out.txt 2>&1 &
PEER_200_PID=$!

./system_peer --topology 3,2,2 \
              -p 700 -i wl0 -a wl0,100,wl0,2000 -a wl0,200,wl0,2000 -a wl0,600,wl0,2000 -a wl0,310,wl0,2000 \
              -t add_identity,800,0,1,3,0+0_1+1 \
              -t enter_net,880,0,1,0,7:0:0,3:0:0,0+0_1+1 \
              -t add_identityarc,1000,1,2+1 \
              -t add_qspnarc,1090,1,2+1 \
              -t add_identityarc,1000,1,3+2 \
              -t add_qspnarc,1090,1,3+2 \
              > test_graph_pid700_out.txt 2>&1 &
PEER_700_PID=$!

./system_peer --topology 3,2,2 \
              -p 600 -i wl0 -a wl0,200,wl0,2000 -a wl0,700,wl0,2000 \
              -t add_identity,1000,0,1,3,0+1_1+1 \
              -t enter_net,1080,0,1,0,6:0:0,4:0:0,0+1_1+1 \
              > test_graph_pid600_out.txt 2>&1 &
PEER_600_PID=$!

./system_peer --topology 3,2,2 \
              -p 500 -i wl0 -a wl0,100,wl0,2000 -a wl0,530,wl0,2000 \
              -t add_identity,1000,0,1,3,0+0 \
              -t enter_net,1080,0,1,0,5:0:0,5:0:0,0+0 \
              -t add_identityarc,1400,1,1+2 \
              -t add_qspnarc,1490,1,1+2 \
              -t check_destnum,3800,1,7,500_knows_5_plus_2 \
              -t check_signal_gnode_split,3800,1,1 \
              > test_graph_pid500_out.txt 2>&1 &
PEER_500_PID=$!

./system_peer --topology 3,2,2 --firstaddr 4,2,2 \
              -p 410 -i wl0 -a wl0,210,wl0,2000 -a wl0,310,wl0,2000 \
              -t add_identityarc,400,0,0+1 \
              -t add_qspnarc,490,0,0+1 \
              -t add_identityarc,600,0,1+1 \
              -t add_qspnarc,690,0,1+1 \
              -t add_identity,1000,0,2,3,0+2_1+2 \
              -t enter_net,1080,0,1,1,1:0,1:0, \
              > test_graph_pid410_out.txt 2>&1 &
PEER_410_PID=$!

./system_peer --topology 3,2,2 \
              -p 210 -i wl0 -a wl0,410,wl0,2000 -a wl0,430,wl0,2000 \
              -t add_identity,400,0,1,3,0+0 \
              -t enter_net,480,0,1,0,2:2:2,1:0:0,0+0 \
              -t add_identity,1000,1,2,3,0+1 \
              -t enter_net,1080,1,2,1,1:0,1:0, \
              -t add_identityarc,1400,2,1+1 \
              -t add_qspnarc,1490,2,1+1 \
              -t check_destnum,3800,2,4,210_knows_2_plus_2 \
              -t check_signal_gnode_split,3800,2,0 \
              > test_graph_pid210_out.txt 2>&1 &
PEER_210_PID=$!

./system_peer --topology 3,2,2 \
              -p 310 -i wl0 -a wl0,410,wl0,2000 -a wl0,700,wl0,2000 \
              -t add_identity,600,0,1,3,0+0 \
              -t enter_net,680,0,1,0,3:2:2,2:0:0,0+0 \
              -t add_identity,1000,1,2,3,0+1_1+1 \
              -t enter_net,1080,1,2,1,1:0,1:0,1+1 \
              > test_graph_pid310_out.txt 2>&1 &
PEER_310_PID=$!

./system_peer --topology 3,2,2 --firstaddr 4,0,0 \
              -p 430 -i wl0 -a wl0,530,wl0,2000 -a wl0,210,wl0,2000 \
              -t add_identityarc,400,0,0+1 \
              -t add_qspnarc,490,0,0+1 \
              -t add_identity,1400,0,2,3,0+2_1+2 \
              -t enter_net,1480,0,1,1,3:0,2:0,1+2 \
              -t remove_qspnarc,2500,1,0,2 \
              > test_graph_pid430_out.txt 2>&1 &
PEER_430_PID=$!

./system_peer --topology 3,2,2 \
              -p 530 -i wl0 -a wl0,430,wl0,2000 -a wl0,630,wl0,2000 -a wl0,500,wl0,2000 \
              -t add_identity,400,0,1,3,0+0 \
              -t enter_net,480,0,1,0,5:0:0,1:0:0,0+0 \
              -t add_identityarc,600,1,1+1 \
              -t add_qspnarc,690,1,1+1 \
              -t add_identity,1400,1,2,3,0+1_1+2_2+1 \
              -t enter_net,1480,1,2,1,3:0,2:0,2+1 \
              -t remove_qspnarc,2500,2,0,1 \
              -t exit_network,3800,2,1 \
              -t check_destnum,4000,2,2,exited \
              > test_graph_pid530_out.txt 2>&1 &
PEER_530_PID=$!

./system_peer --topology 3,2,2 \
              -p 630 -i wl0 -a wl0,530,wl0,2000 -a wl0,730,wl0,2000 \
              -t add_identity,600,0,1,3,0+1 \
              -t enter_net,680,0,1,0,6:0:0,2:0:0,0+1 \
              -t add_identityarc,800,1,1+1 \
              -t add_qspnarc,890,1,1+1 \
              -t add_identity,1400,1,2,3,0+2_1+2 \
              -t enter_net,1480,1,2,1,3:0,2:0, \
              -t exit_network,3800,2,1 \
              -t check_destnum,4000,2,2,exited \
              > test_graph_pid630_out.txt 2>&1 &
PEER_630_PID=$!

./system_peer --topology 3,2,2 \
              -p 730 -i wl0 -a wl0,630,wl0,2000 -a wl0,300,wl0,2000 \
              -t add_identity,800,0,1,3,0+1 \
              -t enter_net,880,0,1,0,7:0:0,3:0:0,0+1 \
              -t add_identity,1400,1,2,3,0+2_1+1 \
              -t enter_net,1480,1,2,1,3:0,2:0,1+1 \
              -t exit_network,3800,2,1 \
              -t check_destnum,4000,2,2,exited \
              > test_graph_pid730_out.txt 2>&1 &
PEER_730_PID=$!


echo Done launches at `date +%T.%N`

sleep 4.2

echo checking status...
PEER_ABORT=0
kill -0 $PEER_100_PID || { wait $PEER_100_PID; echo system_peer 100 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_300_PID || { wait $PEER_300_PID; echo system_peer 300 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_200_PID || { wait $PEER_200_PID; echo system_peer 200 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_700_PID || { wait $PEER_700_PID; echo system_peer 700 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_600_PID || { wait $PEER_600_PID; echo system_peer 600 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_500_PID || { wait $PEER_500_PID; echo system_peer 500 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_410_PID || { wait $PEER_410_PID; echo system_peer 410 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_210_PID || { wait $PEER_210_PID; echo system_peer 210 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_310_PID || { wait $PEER_310_PID; echo system_peer 310 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_430_PID || { wait $PEER_430_PID; echo system_peer 430 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_530_PID || { wait $PEER_530_PID; echo system_peer 530 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_630_PID || { wait $PEER_630_PID; echo system_peer 630 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_730_PID || { wait $PEER_730_PID; echo system_peer 730 prematurely exited with $?; PEER_ABORT=1; }

echo killing...
# interrupt peers
kill $PEER_100_PID $PEER_300_PID $PEER_200_PID $PEER_700_PID $PEER_600_PID \
     $PEER_500_PID $PEER_410_PID $PEER_210_PID $PEER_310_PID $PEER_430_PID \
     $PEER_530_PID $PEER_630_PID $PEER_730_PID

wait $PEER_100_PID $PEER_300_PID $PEER_200_PID $PEER_700_PID $PEER_600_PID \
     $PEER_500_PID $PEER_410_PID $PEER_210_PID $PEER_310_PID $PEER_430_PID \
     $PEER_530_PID $PEER_630_PID $PEER_730_PID

# Ignore errors in this shutdown. Remove any remaining local socket.
rm -f conn_169.254.*
rm -f recv_???_wl0

# kill proxy demons
kill $RADIO_100_PID $RADIO_300_PID $RADIO_200_PID $RADIO_700_PID $RADIO_600_PID \
     $RADIO_500_PID $RADIO_410_PID $RADIO_210_PID $RADIO_310_PID $RADIO_430_PID \
     $RADIO_530_PID $RADIO_630_PID $RADIO_730_PID

wait $RADIO_100_PID $RADIO_300_PID $RADIO_200_PID $RADIO_700_PID $RADIO_600_PID \
     $RADIO_500_PID $RADIO_410_PID $RADIO_210_PID $RADIO_310_PID $RADIO_430_PID \
     $RADIO_530_PID $RADIO_630_PID $RADIO_730_PID

# delay for removal of local sockets (e.g. send_100_wl0)
sleep 0.3

# check PEER_ABORT
test $PEER_ABORT -eq 0 || exit 1
