#!/bin/bash

# Questo script produce una rete di questo tipo:
#
#   1 - 2 - 3 - 4
#
# dove ogni numero indica il pid di un processo (cioè un nodo)
# e i collegamenti sono realizzati con l'iterfaccia radio wl0.
#
# Il nodo 1 prende indirizzo (pseudorandom) :8:0, con anzianità :0:0
# (notare che il primo numero indica il livello 0 e man mano si sale)
# e crea una rete nella quale gli altri nodi, uno alla volta, fanno ingresso.
# Il nodo 2 prende posizione :1:0 con anzianità :1:0.
# I nodi successivi prendono queste posizioni e anzianità:
#   3  :2:0   :2:0
#   4  :3:0   :3:0
#   5  :4:0   :4:0
#   6  :5:0   :5:0
#   7  :6:0   :6:0
#   8  :7:0   :7:0
#   9  :0:0   :8:0
#

radio_domain -i 1_wl0 -o 2_wl0 &
RADIO_1_PID=$!
radio_domain -i 2_wl0 -o 1_wl0 -o 3_wl0 &
RADIO_2_PID=$!
radio_domain -i 3_wl0 -o 2_wl0 -o 4_wl0 &
RADIO_3_PID=$!
radio_domain -i 4_wl0 -o 3_wl0 -o 5_wl0 &
RADIO_4_PID=$!
radio_domain -i 5_wl0 -o 4_wl0 -o 6_wl0 &
RADIO_5_PID=$!
radio_domain -i 6_wl0 -o 5_wl0 -o 7_wl0 &
RADIO_6_PID=$!
radio_domain -i 7_wl0 -o 6_wl0 -o 8_wl0 &
RADIO_7_PID=$!
radio_domain -i 8_wl0 -o 7_wl0 -o 9_wl0 &
RADIO_8_PID=$!
radio_domain -i 9_wl0 -o 8_wl0 -o 10_wl0 &
RADIO_9_PID=$!


sleep 0.3

echo Starting launches at `date +%T.%N`
./system_peer --topology 4,1 -p 1 -i wl0 -a wl0,2,wl0,6000 \
              -t addtag,190,190_goingtoaddarc_1_2 \
              -t add_identityarc,200,0,0+1 \
              -t add_qspnarc,240,0,0+1 \
              -t addtag,280,280_addedarc_1_2 \
              -t addtag,1490,1490_goingtochangecostarc_8_9_15000 \
              -t addtag,1590,1590_goingtochangecostarc_8_9_13000 \
              -t addtag,1690,1690_goingtochangecostarc_8_9_11000 \
              -t addtag,1790,1790_goingtochangecostarc_8_9_8000 \
              -t addtag,1890,1890_goingtochangecostarc_8_9_6000 \
              -t addtag,1990,1990_goingtochangecostarc_8_9_4000 \
              > test_cost_variations_pid1_out.txt 2>&1 &
PEER_1_PID=$!
./system_peer --topology 4,1 -p 2 -i wl0 -a wl0,1,wl0,6000 -a wl0,3,wl0,6000 \
              -t addtag,190,190_goingtoenter_2_witharcs_1 \
              -t add_identity,200,0,0+0 \
              -t enter_net,230,0,1,0,1:0,1:0,0+0 \
              -t addtag,280,280_doneenter_2_witharcs_1 \
              -t addtag,290,290_goingtoaddarc_2_3 \
              -t add_identityarc,300,1,1+1 \
              -t add_qspnarc,340,1,1+1 \
              -t addtag,380,380_addedarc_2_3 \
              -t addtag,1490,1490_goingtochangecostarc_8_9_15000 \
              -t addtag,1590,1590_goingtochangecostarc_8_9_13000 \
              -t addtag,1690,1690_goingtochangecostarc_8_9_11000 \
              -t addtag,1790,1790_goingtochangecostarc_8_9_8000 \
              -t addtag,1890,1890_goingtochangecostarc_8_9_6000 \
              -t addtag,1990,1990_goingtochangecostarc_8_9_4000 \
              -t check_cost_variations,2100 \
              > test_cost_variations_pid2_out.txt 2>&1 &
PEER_2_PID=$!
./system_peer --topology 4,1 -p 3 -i wl0 -a wl0,2,wl0,6000 -a wl0,4,wl0,6000 \
              -t addtag,290,290_goingtoenter_3_witharcs_2 \
              -t add_identity,300,0,0+1 \
              -t enter_net,330,0,1,0,2:0,2:0,0+1 \
              -t addtag,380,380_doneenter_3_witharcs_2 \
              -t addtag,390,390_goingtoaddarc_3_4 \
              -t add_identityarc,400,1,1+1 \
              -t add_qspnarc,440,1,1+1 \
              -t addtag,480,480_addedarc_3_4 \
              -t addtag,1490,1490_goingtochangecostarc_8_9_15000 \
              -t addtag,1590,1590_goingtochangecostarc_8_9_13000 \
              -t addtag,1690,1690_goingtochangecostarc_8_9_11000 \
              -t addtag,1790,1790_goingtochangecostarc_8_9_8000 \
              -t addtag,1890,1890_goingtochangecostarc_8_9_6000 \
              -t addtag,1990,1990_goingtochangecostarc_8_9_4000 \
              > test_cost_variations_pid3_out.txt 2>&1 &
PEER_3_PID=$!
./system_peer --topology 4,1 -p 4 -i wl0 -a wl0,3,wl0,6000 -a wl0,5,wl0,6000 \
              -t addtag,390,390_goingtoenter_4_witharcs_3 \
              -t add_identity,400,0,0+1 \
              -t enter_net,430,0,1,0,3:0,3:0,0+1 \
              -t addtag,480,480_doneenter_4_witharcs_3 \
              -t addtag,490,490_goingtoaddarc_4_5 \
              -t add_identityarc,500,1,1+1 \
              -t add_qspnarc,540,1,1+1 \
              -t addtag,580,580_addedarc_4_5 \
              -t addtag,1490,1490_goingtochangecostarc_8_9_15000 \
              -t addtag,1590,1590_goingtochangecostarc_8_9_13000 \
              -t addtag,1690,1690_goingtochangecostarc_8_9_11000 \
              -t addtag,1790,1790_goingtochangecostarc_8_9_8000 \
              -t addtag,1890,1890_goingtochangecostarc_8_9_6000 \
              -t addtag,1990,1990_goingtochangecostarc_8_9_4000 \
              > test_cost_variations_pid4_out.txt 2>&1 &
PEER_4_PID=$!
./system_peer --topology 4,1 -p 5 -i wl0 -a wl0,4,wl0,6000 -a wl0,6,wl0,6000 \
              -t addtag,490,490_goingtoenter_5_witharcs_4 \
              -t add_identity,500,0,0+1 \
              -t enter_net,530,0,1,0,4:0,4:0,0+1 \
              -t addtag,580,580_doneenter_5_witharcs_4 \
              -t addtag,590,590_goingtoaddarc_5_6 \
              -t add_identityarc,600,1,1+1 \
              -t add_qspnarc,640,1,1+1 \
              -t addtag,680,680_addedarc_5_6 \
              -t addtag,1490,1490_goingtochangecostarc_8_9_15000 \
              -t addtag,1590,1590_goingtochangecostarc_8_9_13000 \
              -t addtag,1690,1690_goingtochangecostarc_8_9_11000 \
              -t addtag,1790,1790_goingtochangecostarc_8_9_8000 \
              -t addtag,1890,1890_goingtochangecostarc_8_9_6000 \
              -t addtag,1990,1990_goingtochangecostarc_8_9_4000 \
              > test_cost_variations_pid5_out.txt 2>&1 &
PEER_5_PID=$!
./system_peer --topology 4,1 -p 6 -i wl0 -a wl0,5,wl0,6000 -a wl0,7,wl0,6000 \
              -t addtag,590,590_goingtoenter_6_witharcs_5 \
              -t add_identity,600,0,0+1 \
              -t enter_net,630,0,1,0,5:0,5:0,0+1 \
              -t addtag,680,680_doneenter_6_witharcs_5 \
              -t addtag,690,690_goingtoaddarc_6_7 \
              -t add_identityarc,700,1,1+1 \
              -t add_qspnarc,740,1,1+1 \
              -t addtag,780,780_addedarc_6_7 \
              -t addtag,1490,1490_goingtochangecostarc_8_9_15000 \
              -t addtag,1590,1590_goingtochangecostarc_8_9_13000 \
              -t addtag,1690,1690_goingtochangecostarc_8_9_11000 \
              -t addtag,1790,1790_goingtochangecostarc_8_9_8000 \
              -t addtag,1890,1890_goingtochangecostarc_8_9_6000 \
              -t addtag,1990,1990_goingtochangecostarc_8_9_4000 \
              -t check_cost_variations,2100 \
              > test_cost_variations_pid6_out.txt 2>&1 &
PEER_6_PID=$!
./system_peer --topology 4,1 -p 7 -i wl0 -a wl0,6,wl0,6000 -a wl0,8,wl0,6000 \
              -t addtag,690,690_goingtoenter_7_witharcs_6 \
              -t add_identity,700,0,0+1 \
              -t enter_net,730,0,1,0,6:0,6:0,0+1 \
              -t addtag,780,780_doneenter_7_witharcs_6 \
              -t addtag,790,790_goingtoaddarc_7_8 \
              -t add_identityarc,800,1,1+1 \
              -t add_qspnarc,840,1,1+1 \
              -t addtag,880,880_addedarc_7_8 \
              -t addtag,1490,1490_goingtochangecostarc_8_9_15000 \
              -t addtag,1590,1590_goingtochangecostarc_8_9_13000 \
              -t addtag,1690,1690_goingtochangecostarc_8_9_11000 \
              -t addtag,1790,1790_goingtochangecostarc_8_9_8000 \
              -t addtag,1890,1890_goingtochangecostarc_8_9_6000 \
              -t addtag,1990,1990_goingtochangecostarc_8_9_4000 \
              -t check_cost_variations,2100 \
              > test_cost_variations_pid7_out.txt 2>&1 &
PEER_7_PID=$!
./system_peer --topology 4,1 -p 8 -i wl0 -a wl0,7,wl0,6000 -a wl0,9,wl0,6000 \
              -t addtag,790,790_goingtoenter_8_witharcs_7 \
              -t add_identity,800,0,0+1 \
              -t enter_net,830,0,1,0,7:0,7:0,0+1 \
              -t addtag,880,880_doneenter_8_witharcs_7 \
              -t addtag,890,890_goingtoaddarc_8_9 \
              -t add_identityarc,900,1,1+1 \
              -t add_qspnarc,940,1,1+1 \
              -t addtag,980,980_addedarc_8_9 \
              -t addtag,1490,1490_goingtochangecostarc_8_9_15000 \
              -t changecost_arc,1500,1,15000 \
              -t addtag,1580,1580_changedcostarc_8_9 \
              -t addtag,1590,1590_goingtochangecostarc_8_9_13000 \
              -t changecost_arc,1600,1,13000 \
              -t addtag,1680,1680_changedcostarc_8_9 \
              -t addtag,1690,1690_goingtochangecostarc_8_9_11000 \
              -t changecost_arc,1700,1,11000 \
              -t addtag,1780,1780_changedcostarc_8_9 \
              -t addtag,1790,1790_goingtochangecostarc_8_9_8000 \
              -t changecost_arc,1800,1,8000 \
              -t addtag,1880,1880_changedcostarc_8_9 \
              -t addtag,1890,1890_goingtochangecostarc_8_9_6000 \
              -t changecost_arc,1900,1,6000 \
              -t addtag,1980,1980_changedcostarc_8_9 \
              -t addtag,1990,1990_goingtochangecostarc_8_9_4000 \
              -t changecost_arc,2000,1,4000 \
              -t addtag,2080,2080_changedcostarc_8_9 \
              -t check_cost_variations,2100 \
              > test_cost_variations_pid8_out.txt 2>&1 &
PEER_8_PID=$!
./system_peer --topology 4,1 -p 9 -i wl0 -a wl0,8,wl0,6000 -a wl0,10,wl0,6000 \
              -t addtag,890,890_goingtoenter_9_witharcs_8 \
              -t add_identity,900,0,0+1 \
              -t enter_net,930,0,1,0,0:0,8:0,0+1 \
              -t addtag,980,980_doneenter_9_witharcs_8 \
              > test_cost_variations_pid9_out.txt 2>&1 &
PEER_9_PID=$!
echo Done launches at `date +%T.%N`

sleep 5

echo killing...
# interrupt peers
kill $PEER_1_PID $PEER_2_PID $PEER_3_PID $PEER_4_PID $PEER_5_PID $PEER_6_PID \
     $PEER_7_PID $PEER_8_PID $PEER_9_PID

# wait for peers and note down its retval
wait $PEER_1_PID
PEER_1_RET=$?
wait $PEER_2_PID
PEER_2_RET=$?
wait $PEER_3_PID
PEER_3_RET=$?
wait $PEER_4_PID
PEER_4_RET=$?
wait $PEER_5_PID
PEER_5_RET=$?
wait $PEER_6_PID
PEER_6_RET=$?
wait $PEER_7_PID
PEER_7_RET=$?
wait $PEER_8_PID
PEER_8_RET=$?
wait $PEER_9_PID
PEER_9_RET=$?

# kill proxy demons
kill $RADIO_1_PID $RADIO_2_PID $RADIO_3_PID $RADIO_4_PID $RADIO_5_PID $RADIO_6_PID \
     $RADIO_7_PID $RADIO_8_PID $RADIO_9_PID

# delay for removal of local sockets (e.g. send_1_wl0)
sleep 0.3

# check testers retval
test $PEER_1_RET -eq 0 || exit 1
test $PEER_2_RET -eq 0 || exit 2
test $PEER_3_RET -eq 0 || exit 3
test $PEER_4_RET -eq 0 || exit 4
test $PEER_5_RET -eq 0 || exit 5
test $PEER_6_RET -eq 0 || exit 6
test $PEER_7_RET -eq 0 || exit 7
test $PEER_8_RET -eq 0 || exit 8
test $PEER_9_RET -eq 0 || exit 9
